# Generated by Django 5.2.1 on 2025-09-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilePreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blob_name', models.CharField(max_length=500, unique=True)),
                ('signed_url', models.URLField()),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
