# Generated by Django 5.2.1 on 2025-09-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_alter_filepreview_blob_name_usuariomicrosoft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filepreview',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='filepreview',
            name='signed_url',
        ),
        migrations.AddField(
            model_name='filepreview',
            name='preview_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filepreview',
            name='preview_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filepreview',
            name='blob_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='UsuarioMicrosoft',
        ),
    ]
