# Generated by Django 5.2.1 on 2025-09-29 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0003_remove_filepreview_expires_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filepreview',
            old_name='preview_expiration',
            new_name='expires_at',
        ),
        migrations.RenameField(
            model_name='filepreview',
            old_name='preview_url',
            new_name='signed_url',
        ),
    ]
