# Generated by Django 5.2.1 on 2025-10-13 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft_auth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilePreview',
        ),
    ]
