# Generated by Django 5.2.1 on 2025-10-29 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Documentos_StateMachine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentotecnico',
            name='equipos_aprobadores',
        ),
        migrations.RemoveField(
            model_name='documentotecnico',
            name='equipos_redactores',
        ),
        migrations.RemoveField(
            model_name='documentotecnico',
            name='equipos_revisores',
        ),
        migrations.DeleteModel(
            name='Equipo',
        ),
        migrations.DeleteModel(
            name='DocumentoTecnico',
        ),
    ]
