# Generated by Django 5.2.1 on 2025-06-15 19:36

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('estado', django_fsm.FSMField(choices=[('iniciado', 'Iniciado'), ('en_redaccion', 'En redacción'), ('en_revision', 'En revisión'), ('corregir', 'Corrección'), ('aprobado', 'Aprobado'), ('finalizado', 'Finalizado')], default='iniciado', max_length=50, protected=True)),
                ('equipos_aprobadores', models.ManyToManyField(related_name='docs_aprobados', to='documentos.equipo')),
                ('equipos_redactores', models.ManyToManyField(related_name='docs_redactados', to='documentos.equipo')),
                ('equipos_revisores', models.ManyToManyField(related_name='docs_revisados', to='documentos.equipo')),
            ],
        ),
    ]
